alias attachadmin='sudo geth attach /var/lib/goethereum/mainnet/geth.ipc'
alias temp='sensors'
alias h='history'
alias dc='docker-compose'
alias h='history'
alias t='tail -500f'
alias s='sudo systemctl'
alias lighthousebeacon='journalctl -u lighthousebeacon -f --output cat --line=100'
alias lighthousevalidator='journalctl -u lighthousevalidator -f --output cat --line=100'
alias goeth='journalctl -u geth -f --output cat --line=100'
alias i='sudo iotop'
alias logopenethereum='journalctl -u openethereum -f --output cat --line=100'
alias editbeacon='sudo nano /etc/systemd/system/lighthousebeacon.service'
alias editvalidator='sudo nano /etc/systemd/system/lighthousevalidator.service'
alias editgeth='sudo nano /etc/systemd/system/geth.service'
