global:
    scrape_interval: 15s

    external_labels:
        monitor: 'lighthouse-docker'

scrape_configs:
    - job_name: 'local-lighthouse'
      scrape_interval: 5s
      file_sd_configs:
          - files:
              - '/prometheus/targets/scrape-targets.json'
    - job_name: 'geth'
      metrics_path: /debug/metrics/prometheus
      scrape_interval: 5s
      scheme: http
      static_configs:
      - targets:
        - localhost:6060
